// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHwKaUGn79hx-823GPW0QzaPGvcwQGh1s',
    appId: '1:490233824809:web:a0b52d518e2eb6d6a43e38',
    messagingSenderId: '490233824809',
    projectId: 'fastfueltag',
    authDomain: 'fastfueltag.firebaseapp.com',
    storageBucket: 'fastfueltag.appspot.com',
    measurementId: 'G-LM6FV9NKP7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDADuiphQlYfwwMDMGYoVCRfqg87gpgQY',
    appId: '1:490233824809:android:919cb115ae87f217a43e38',
    messagingSenderId: '490233824809',
    projectId: 'fastfueltag',
    storageBucket: 'fastfueltag.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBRpekc4Y62oiPIvBiVKcHjiyy1Obc5Hg',
    appId: '1:490233824809:ios:ae429c2cbf2975eda43e38',
    messagingSenderId: '490233824809',
    projectId: 'fastfueltag',
    storageBucket: 'fastfueltag.appspot.com',
    iosClientId: '490233824809-vekj3k0m6e1me8e6lk9jpgm7n3ta3oe5.apps.googleusercontent.com',
    iosBundleId: 'com.example.fastFuelTag',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBRpekc4Y62oiPIvBiVKcHjiyy1Obc5Hg',
    appId: '1:490233824809:ios:fc676839fc8dac7ea43e38',
    messagingSenderId: '490233824809',
    projectId: 'fastfueltag',
    storageBucket: 'fastfueltag.appspot.com',
    iosClientId: '490233824809-jf066c08411366mg05t7i5l843cf5dip.apps.googleusercontent.com',
    iosBundleId: 'com.example.fastFuelTag.RunnerTests',
  );
}
